// This file was generated by Prisma, and assumes you run Prisma commands using `bun --bun run prisma [command]`.
import { defineConfig, env } from "prisma/config";

const DB_URL = Bun.env.DATABASE_URL;
export default defineConfig({
  schema: "./src/infrastructure/external/database/prisma/schema.prisma",
  migrations: {
    path: "./src/infrastructure/external/database/prisma/migrations",
  },
  datasource: {
    url: DB_URL || env("DATABASE_URL"),
  },
});

console.log(DB_URL);
